### ISSUE TITLE
Speed_E7_05 is actually two commands

### ISSUE THREAD

**Issue by jnweiger** [kkaempf/ruida#1]
```
Speed_E7_05 00 c9 04 00 100.0mm/s    e7 05 00 c9 04 00 00 00 06 0d 20
```
should be parsed as
```
Unknown command                      e7 05 00
```
Followed by
``` 
Speed Layer 0 100.0mm/s              c9 04 00 00 00 06 0d 20
```
Other example:
```
Speed Layer 1 30.0mm/s               c9 04 01 00 00 01 6a 30

**Comment by kkaempf** [comment]
Apparently, all commands are 0x80-0xff while all values are 0x00-0x7f (see color encoding in #5)

**Comment by jnweiger** [comment]
Ah, right. A command always starts with MSB set, and MSB is only set at command start. 
The RGB value is actually just combined into one integer and then encoded in the usual 5byte number format. But yeah that also ensures that the MSB remains unused.
