### ISSUE TITLE
Regenerating the RD file?

### ISSUE THREAD

**Issue by cbrum11** [kkaempf/ruida#7]
First, thanks for creating this great tool!  

I've got a need to manipulate some of the coordinates in an RD file, then run the manipulated RD file on the laser.  As a test, I'm using python to apply a simple offset to the coordinates your tool allows me to extract... but is there a simple way to recompile/recreate the RD file in a way the Ruida controller accepts after manipulation?

Thanks!

**Comment by kkaempf** [comment]
Uhm, this tool could do this (with a lot of work). But I suspect that some commands could make this possible (like `E7 04` or `Layer_Top_Left_E7_52`). Need to run some experiments ...
