### ISSUE TITLE
DA 00 XX XX - get XX XX from machine

### ISSUE THREAD

**Issue by ghost** [kkaempf/ruida#9]
I dream make my own hardware compatible with RDWorks. Reading RD-file from SD-card is not a problem. But communication with RDWorks software is a problem. I noticed that I should response in the following way DA 01 XX XX \<VALUE\>. For example, when I press any button in RDWorks it's first send DA 00 05 7E. But I don't found information about this commands, anyone has decoded this?

**Comment by kkaempf** [comment]
Sorry, no. Up to now I only know that 3 bytes are following `DA`. But I do not know their meaning.
